# See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "0.11"
before_install: npm install -g grunt-cli
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
after_success:
  - npm run docs
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=urbanetic/aurin-esp
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f app/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
