sudo: required
language: node_js
node_js:
  - '0.11'
services:
  - docker
env:
  global:
    - secure: WmKPI/+e80p366je8ZFOHLsh7nz/U19pJpAgAtUtDqgxKW/ROpabFAoW9QsG0VeVtME5stlQ1DTdzHtCdDx4kEGwOQNBzESvLPIPsfM9fqN/nzfW/HxwqD6QVXD+zcNt9jgzzlJ1rrh/EFj3VAUxr6GpT9KrO3Sir9gVHT2tM3k=
    - secure: gjhllqeNOCgp9UyDPNX9apnyQ7ikyJcR3+SDiGchfAvgUiUMuVfazb+YlvEo3jcg3iN2SOXjfgALVL1d+ieXrHYvzvOwJk5vo+Tfq36WkJmvcT5BWSk4xyXCzjkpOcqutsmCSXQIRzN4fNatZwTR2p0QbAKiZfcjSc4s60vfsUw=
    - secure: FkqxXIaZJMZsDrvWzhIY2atJf/Fdnf0FdNqFnYaP0TzqSse8RuLHbQWWoDmgfWZqOYGyg9uD7qUIBl1+qCUf/s1mQBgW6zkz+eqqrcM1WzJUjNiMdwUNJhHX7FD6uN1ofxgaJ1k6xSSmvsF+XWNWOWe4Co1mM/Cn0XMrLUEXdks=
    - COMMIT=${TRAVIS_COMMIT::8}

before_install: npm install -g grunt-cli bower@1.7.9
install: npm install
before_script: npm run build
script: echo "Nothing to test"

after_success:
  - npm run docs
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=urbanetic/aurin-esp
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | sed 's#/#_#g' ; fi`
  - echo "Building Docker image $REPO:$TAG"
  - pushd app
  - docker build -f Dockerfile -t $REPO:$TAG .
  - popd
  - docker push $REPO
