sudo: required
language: node_js
node_js:
  - '0.11'
services:
  - docker

before_install: npm install -g grunt-cli bower@1.7.9
install: npm install
before_script: npm run build
script: echo "Nothing to test"

after_success:
  - npm run docs
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=urbanetic/aurin-esp
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f app/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
env:
  global:
    - secure: Khzo2xwOnc5HXwmqFnjMQmlhIdFvb/5MbVMdhd3cWSu/K+izyjS4WVCT+WVnoHPmFSLqKlnxvz2AGs3TFeaWuJO1gM4mZHpkTHfKJNgn58JkgEGUlU9xmfBEiBwZ0rFDhTV2llPEMIYaryv/mbsUjEBvqY0krJGbf3Xm4pWIc/Q=
    - secure: S0l5lJhxwX2VKYNUrRydnroJeFpTrxVl6x797jG8NEs5HDs/yWChyBINsN9y20/oAVDL04M1snP/EHr4CGnF0mrEWYlFSrMOii0qSqDD3pL8S3OEUPOB/ZsoQbmkV71GryvZ+3L0B4Uoseu2iLC58CnvhqX+jvQ6RsWFTX3p3Dw=
    - secure: dHaZMxgyQw2M39gnet6QKO21GLQMIFQHZx/xKymMDs1EzP+2KSaP2j9WufeffpWvheAwqOgH19xhJRi5RGV/pOLZADJbsitjcS3SMfX+diy9DBU1cSOB++ypSn8mbtcIQZOw0BDBXQgIbbyUfGKOfMrPDx2vFu52GMp+CxY2R0o=
    - COMMIT=${TRAVIS_COMMIT::8}
